# Generated by Django 4.2.7 on 2023-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='changing_date',
            field=models.DateField(default='2023-01-01', verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateField(default='2023-01-01', verbose_name='Дата создания'),
        ),
    ]
